#!/bin/sh
echo 'sd card will not mount unless calculator runs as a seperate process'
# docker run --privileged -it --rm -e DISPLAY=$DISPLAY -v /Volumes/X49GP:/Volumes/X49GP -v /tmp/.X11-unix:/tmp/.X11-unix --device /dev/snd c4pt/x49gp-current 
# in docker container # x49gp --reflash=/2MB_215f.bin
sleep 2
docker run --privileged -it --rm -e DISPLAY=$DISPLAY -v /Volumes/X49GP:/Volumes/X49GP -v /tmp/.X11-unix:/tmp/.X11-unix --device /dev/snd c4pt/x49gp-current x49gp --reflash=/2MB_215f.bin
 
